async-std: 1.6.0 -> 1.5.0
Seems to cause an issue with the executors somehow.

    thread 'main' panicked at 'cannot run an executor inside another executor', <::std::macros::panic macros>:2:4