nixpkgs: 2020-02-19 -> 2020-05-19
It seems like the latest crate2nix depends on some changes to the rust
infrastructure in nixpkgs.

    error: cannot coerce null to a string, at pkgs/build-support/rust/build-rust-crate/configure-crate.nix:33:4